services:
  yuuki-computer:
    build: .
    container_name: yuuki-computer
    ports:
      - "127.0.0.1:3022:22"
    restart: unless-stopped
    hostname: computer
    volumes:
      - /home/shaurya/.ssh/keys/yuuki-container/yuuki.pub:/home/yuuki/.ssh/authorized_keys:ro
      - /home/shaurya/.ssh/keys/azure/azure:/home/yuuki/.ssh/azure:ro
      - /home/shaurya/.ssh/keys/gh/lil-yuuki/gh_lil-yuuki:/home/yuuki/.ssh/gh:ro

      - /work:/home/yuuki/work:rw
      - /storage/yuuki:/storage/yuuki:rw
    # environment:
    networks:
      route64-ipv6:
        ipv6_address: fd00:1d10::100a

networks:
  route64-ipv6:
    external: true
